services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - proseeker-pg_db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    networks:
      - db_network

  redis:
    image: redis
    command: redis-server
    restart: on-failure
    volumes:
      - proseeker-pg_redis:/data
    networks:
      - redis_network

  sidekiq:
    build: .
    restart: on-failure
    command: bundle exec sidekiq
    env_file:
      - .env.docker
    volumes:
      - .:/usr/src/proseeker
      - /usr/src/proseeker/tmp # don't mount tmp directory
    networks:
      - db_network
      - redis_network
    depends_on:
      - web

  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/usr/src/proseeker
    command: bash -c "bin/setup && rails server -b 0.0.0.0"
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    networks:
      - default
      - db_network
      - redis_network
    depends_on:
      - db
      - redis

volumes:
  proseeker-pg_db:
  proseeker-pg_redis:
networks:
  db_network:
    external: false
  redis_network:
    external: false
